<template>
    <div id="masvideos_movies_year_filter-1" class="widget masvideos masvideos-widget_movies_year_filter">
        <div class="widget-header"><span class="widget-title">연도별</span></div>
        <ul>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2023"><span>2023</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2022"><span>2022</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2021"><span>2021</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2020"><span>2020</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2019"><span>2019</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2018"><span>2018</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2017"><span>2017</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2016"><span>2016</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2015"><span>2015</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2014"><span>2014</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2013"><span>2013</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2012"><span>2012</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2011"><span>2011</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2010"><span>2010</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2009"><span>2009</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2008"><span>2008</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2007"><span>2007</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2006"><span>2006</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2005"><span>2005</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2004"><span>2004</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2003"><span>2003</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2002"><span>2002</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2001"><span>2001</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=2000"><span>2000</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1999"><span>1999</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1998"><span>1998</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1997"><span>1997</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1996"><span>1996</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1995"><span>1995</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1994"><span>1994</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1993"><span>1993</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1992"><span>1992</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1991"><span>1991</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1990"><span>1990</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1989"><span>1989</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1988"><span>1988</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1987"><span>1987</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1986"><span>1986</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1985"><span>1985</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1984"><span>1984</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1983"><span>1983</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1982"><span>1982</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1981"><span>1981</span> </a></li>
        <li class="masvideos-layered-nav-movies-year"><a
                href="/?year_filter=1980"><span>1980</span> </a></li>
    </ul>
</div></template>